[template]
src = "auth0-idp.tmpl"
dest = "/etc/apache2/mellon/auth0.idp-metadata.xml"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
    "/config/auth0"
]

reload_cmd = "/usr/sbin/apachectl graceful"

