[template]
src = "iplimit.tmpl"
dest = "/var/www/irc-iplimit/iplimit.conf"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

keys = [
    "/config"
]

reload_cmd = "/etc/init.d/apache2 restart"
